# Generated by Django 3.2.8 on 2023-01-17 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rosa',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('variedad', models.CharField(max_length=100, verbose_name='Variedad')),
                ('imagen', models.ImageField(null=True, upload_to='imagenes/', verbose_name='Imagen')),
                ('descripcion', models.TextField(null=True, verbose_name='Descripcion')),
            ],
        ),
    ]
